---
version: "2"
checks:
  # This is one of the default quality checks that are always enabled in CI, so
  # must be configured separately to more closely match other rules we use, such
  # as eslint.
  # The threshold below is taken from the `sonarjs/recommended` eslint plugin.
  # ref: https://docs.codeclimate.com/docs/advanced-configuration#default-checks
  method-complexity:
    config:
      threshold: 15
