include:
  - project: dwp/engineering/gitlab-ci-toolbox
    ref: 3.x.x
    file: blueprints/node.yml
  - project: dwp/engineering/gitlab-ci-toolbox
    ref: 3.x.x
    file: blueprints/auto-tag-merge.yml
  - project: dwp/engineering/gitlab-ci-toolbox
    ref: 3.x.x
    file: templates/build-docker-image.yml
  - template: DAST.latest.gitlab-ci.yml

variables:
  NODE_IMAGE: node:14-alpine@sha256:2ae9624a39ce437e7f58931a5747fdc60224c6e40f8980db90728de58e22af7c
  NODE_PUBLISH_TO_GITLAB: "true"

# Build the dist/ folder for subsequent stages
build-static-assets:
  extends: .node-common
  stage: build
  script: npm run compile-static-assets
  artifacts:
    expire_in: 1 day
    paths:
      - dist/
