include:
  - template: DAST.gitlab-ci.yml
  - project: dwp/engineering/gitlab-ci-toolbox
    ref: 3.x.x
    file: blueprints/node.yml
  - project: dwp/engineering/gitlab-ci-toolbox
    ref: 3.x.x
    file: blueprints/auto-tag-merge.yml
  - project: dwp/engineering/gitlab-ci-toolbox
    ref: 3.x.x
    file: templates/build-docker-image.yml

variables:
  NODE_IMAGE: node:14-alpine@sha256:2ae9624a39ce437e7f58931a5747fdc60224c6e40f8980db90728de58e22af7c
  NODE_PUBLISH_TO_GITLAB: "true"

# Build the dist/ folder for subsequent stages
build-static-assets:
  extends: .node-common
  stage: build
  script: npm run compile-static-assets
  artifacts:
    expire_in: 1 day
    paths:
      - dist/

# Package up a testable CASA application, ready for dyanmic security tests
zap-package:
  extends: .toolbox-build-docker-image
  stage: package
  variables:
    DOCKERFILE: test/penetration/Dockerfile

dast:
  stage: security-dynamic-analysis
  tags:
    - docker-in-docker-privileged
  needs:
    - zap-package
  variables:
    DAST_WEBSITE: http://casa-pentest-app:3000/
    DAST_FULL_SCAN_ENABLED: "true"
  services:
    - name: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
      alias: casa-pentest-app
  