include:
  - project: dwp/engineering/gitlab-ci-toolbox
    ref: 3.x.x
    file: blueprints/node.yml
  - project: dwp/engineering/gitlab-ci-toolbox
    ref: 3.x.x
    file: blueprints/auto-tag-merge.yml

variables:
  NODE_IMAGE: node:14.18.1@sha256:36a56dc5c28c952b77db095e986e6e65af7eb9095e38b0da7495fc83800b91af
  NODE_PUBLISH_TO_GITLAB: "true"

# ---------------------------------------------------------- blueprint overrides

node-coverage:
  variables:
    TEST_EXECUTABLE: 'npm run test:combined'

# This is an OSS project so the @dwp scope point to public npm registry. However
# for publishing to the internal GitLab we need to remove that specific config.
node-publish-gitlab:
  before_script:
    - if [ -f .npmrc ]; then sed -i.bak '/^@dwp:registry.*$/d' .npmrc; fi

# ------------------------------------------------------------------ custom jobs

e2e-dast:
  stage: security-dynamic-analysis
  image: $NODE_IMAGE
  tags:
    - docker
  services:
    - name: owasp/zap2docker-stable@sha256:fa9c69ef7b4b5c6395df2fa50b40146651b87b6a0b019f97d930532bb4e79214
      alias: zap
      entrypoint: [""]
      command: ["zap.sh", "-daemon", "-host", "0.0.0.0", "-port", "8080", "-config", "api.key=secret", "-config", "api.addrs.addr.name=.*", "-config", "api.addrs.addr.regex=true"]
  needs:
    - node-modules
  variables:
    # ref: https://docs.gitlab.com/runner/executors/docker.html#create-a-network-for-each-job
    # Required so ZAP can connect to servers being spun up in this build container
    FF_NETWORK_PER_BUILD: 1
  script:
    - "until wget -qO- --header 'X-ZAP-Api-Key: secret' http://zap:8080/JSON/core/view/zapHomePath >/dev/null 2>&1; do echo 'Waiting for ZAP ...'; sleep 1; done"
    # We use `|| true` here in order to always generate the report, regardless
    # of failure. We also limit the no. workers so not to overload ZAP (the
    # execution environment is quite constrained)
    - npm run test:e2e -- --workers 4 --zap --zap-proxy 'http://zap:8080/' --zap-target-hostname "$(hostname)" || true
    - "wget -qO- --header 'X-ZAP-Api-Key: secret' http://zap:8080/OTHER/core/other/jsonreport > gl-dast-report.json"
  artifacts:
    when: always
    reports:
      dast:
        - gl-dast-report.json
